FROM python:3

RUN mkdir /bsap
ADD bsap/ /bsap

# The emulator runs on port 1235 which redirects to host port 1120.
EXPOSE 1235/udp 1120/udp
EXPOSE 1235/tcp 1120/tcp

RUN pip install -r /bsap/requirements.txt

#CMD python /bsap/bsapmodule.py --address 0
CMD [ "bash" ]
