// Generated by binpac_quickstart

#include "plugin/Plugin.h"

#include "BSAP.h"

namespace plugin {
namespace BYU_INL_BSAP {

class Plugin : public plugin::Plugin {
public:
	plugin::Configuration Configure()
		{
		DBG_LOG(DBG_PLUGINS, "Got initialized!CapstoneBros");

		AddComponent(new ::analyzer::Component("BSAP",
		             ::analyzer::BSAP::BSAP_Analyzer::InstantiateAnalyzer));

		plugin::Configuration config;
		config.name = "BYU_INL::BSAP";
		config.description = "Emerson/Bristol-Babcock BSAP Protocol analyzer";
		return config;
		}
} plugin;

}
}
